version: "3.9"

services:
  workspace:
    build:
      context: .
      dockerfile: ./docker/workspace/Dockerfile
    container_name: go-openai-client-workspace
    tty: true
    volumes:
      - .:/go/src/github.com/mkaiho/go-openai-client
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /go/src/github.com/mkaiho/go-openai-client
